-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matmul is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    in1_ce0 : OUT STD_LOGIC;
    in1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    in2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    in2_ce0 : OUT STD_LOGIC;
    in2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    out_r_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_r_ce0 : OUT STD_LOGIC;
    out_r_we0 : OUT STD_LOGIC;
    out_r_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    size : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of matmul is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matmul_matmul,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=4101,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=645,HLS_SYN_LUT=641,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_100 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln6_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_delayed : STD_LOGIC;
    signal size_read_reg_484 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln6_reg_489 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln6_reg_489_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_493 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_493_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_493_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln15_fu_309_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln15_reg_498 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln15_reg_498_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln15_reg_498_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln11_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_reg_513 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_reg_513_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_reg_513_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_reg_518 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_reg_518_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_reg_518_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_reg_523 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_159_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln12_reg_538 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_icmp_ln78_phi_fu_141_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_init_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_mux_icmp_ln97_phi_fu_152_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln12_1_fu_325_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln12_2_fu_344_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln15_1_fu_420_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten131_fu_68 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal add_ln6_1_fu_198_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_indvar_flatten131_load : STD_LOGIC_VECTOR (11 downto 0);
    signal i_fu_72 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal i_3_fu_253_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten3_fu_76 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal select_ln7_1_fu_376_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal j_fu_80 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal j_3_fu_289_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal k_fu_84 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal k_3_fu_358_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sum_fu_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sum_1_fu_429_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal in1_ce0_local : STD_LOGIC;
    signal in2_ce0_local : STD_LOGIC;
    signal out_r_we0_local : STD_LOGIC;
    signal out_r_ce0_local : STD_LOGIC;
    signal xor_ln6_fu_241_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln6_fu_227_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln6_fu_233_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal and_ln6_fu_247_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_mid2_fu_277_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln7_fu_265_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln7_fu_261_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_297_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln15_fu_305_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln12_fu_315_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln12_fu_319_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_6_fu_285_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_330_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln12_1_fu_338_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln9_fu_349_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln7_1_fu_370_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sum_mid2_fu_413_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_4_fu_424_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_164 : BOOLEAN;
    signal ap_condition_162 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component matmul_mul_32s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component matmul_flow_control_loop_delay_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_loop_exit_ready_delayed : IN STD_LOGIC );
    end component;



begin
    mul_32s_32s_32_2_1_U1 : component matmul_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => in2_q0,
        din1 => in1_q0,
        ce => ap_const_logic_1,
        dout => grp_fu_159_p2);

    flow_control_loop_delay_pipe_U : component matmul_flow_control_loop_delay_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1,
        ap_loop_exit_ready_delayed => ap_loop_exit_ready_delayed);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter4_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_0))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_const_logic_0;
            elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
            end if; 
        end if;
    end process;

    i_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1))) then 
                    i_fu_72 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_fu_72 <= i_3_fu_253_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten131_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_164)) then
                indvar_flatten131_fu_68 <= add_ln6_1_fu_198_p2;
            end if;
        end if;
    end process;

    indvar_flatten3_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1))) then 
                    indvar_flatten3_fu_76 <= ap_const_lv10_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    indvar_flatten3_fu_76 <= select_ln7_1_fu_376_p3;
                end if;
            end if; 
        end if;
    end process;

    j_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1))) then 
                    j_fu_80 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_fu_80 <= j_3_fu_289_p3;
                end if;
            end if; 
        end if;
    end process;

    k_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1))) then 
                    k_fu_84 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    k_fu_84 <= k_3_fu_358_p2;
                end if;
            end if; 
        end if;
    end process;

    sum_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if ((ap_const_boolean_1 = ap_condition_162)) then 
                    sum_fu_88 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    sum_fu_88 <= sum_1_fu_429_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln15_reg_498 <= add_ln15_fu_309_p2;
                ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage0;
                ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                ap_loop_init_pp0_iter1_reg <= ap_loop_init;
                empty_reg_493 <= empty_fu_271_p2;
                icmp_ln11_reg_513 <= icmp_ln11_fu_353_p2;
                icmp_ln6_reg_489 <= icmp_ln6_fu_204_p2;
                icmp_ln6_reg_489_pp0_iter1_reg <= icmp_ln6_reg_489;
                size_read_reg_484 <= size;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln15_reg_498_pp0_iter2_reg <= add_ln15_reg_498;
                add_ln15_reg_498_pp0_iter3_reg <= add_ln15_reg_498_pp0_iter2_reg;
                ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                empty_reg_493_pp0_iter2_reg <= empty_reg_493;
                empty_reg_493_pp0_iter3_reg <= empty_reg_493_pp0_iter2_reg;
                icmp_ln11_reg_513_pp0_iter2_reg <= icmp_ln11_reg_513;
                icmp_ln11_reg_513_pp0_iter3_reg <= icmp_ln11_reg_513_pp0_iter2_reg;
                icmp_ln9_reg_518_pp0_iter2_reg <= icmp_ln9_reg_518;
                icmp_ln9_reg_518_pp0_iter3_reg <= icmp_ln9_reg_518_pp0_iter2_reg;
                mul_ln12_reg_538 <= grp_fu_159_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln7_reg_523 <= icmp_ln7_fu_384_p2;
                icmp_ln9_reg_518 <= icmp_ln9_fu_364_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln12_1_fu_338_p2 <= std_logic_vector(unsigned(tmp_1_fu_330_p3) + unsigned(zext_ln15_fu_305_p1));
    add_ln12_fu_319_p2 <= std_logic_vector(unsigned(tmp_fu_297_p3) + unsigned(zext_ln12_fu_315_p1));
    add_ln15_fu_309_p2 <= std_logic_vector(unsigned(tmp_fu_297_p3) + unsigned(zext_ln15_fu_305_p1));
    add_ln6_1_fu_198_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten131_load) + unsigned(ap_const_lv12_1));
    add_ln6_fu_227_p2 <= std_logic_vector(unsigned(i_fu_72) + unsigned(ap_const_lv5_1));
    add_ln7_1_fu_370_p2 <= std_logic_vector(unsigned(indvar_flatten3_fu_76) + unsigned(ap_const_lv10_1));
    add_ln7_fu_265_p2 <= std_logic_vector(unsigned(select_ln6_fu_233_p3) + unsigned(ap_const_lv5_1));
    and_ln6_fu_247_p2 <= (xor_ln6_fu_241_p2 and ap_phi_mux_icmp_ln97_phi_fu_152_p4);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_162_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init)
    begin
                ap_condition_162 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1));
    end process;


    ap_condition_164_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_164 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln6_fu_204_p2)
    begin
        if (((icmp_ln6_fu_204_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_loop_exit_ready_delayed_assign_proc : process(ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg))) then 
            ap_loop_exit_ready_delayed <= ap_const_logic_1;
        else 
            ap_loop_exit_ready_delayed <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_icmp_ln78_phi_fu_141_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln6_reg_489_pp0_iter1_reg, icmp_ln7_reg_523, ap_loop_init_pp0_iter1_reg, ap_block_pp0_stage0)
    begin
        if (((icmp_ln6_reg_489_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_phi_mux_icmp_ln78_phi_fu_141_p4 <= icmp_ln7_reg_523;
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_phi_mux_icmp_ln78_phi_fu_141_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_icmp_ln78_phi_fu_141_p4 <= icmp_ln7_reg_523;
        end if; 
    end process;


    ap_phi_mux_icmp_ln97_phi_fu_152_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln6_reg_489_pp0_iter1_reg, icmp_ln9_reg_518, ap_loop_init_pp0_iter1_reg, ap_block_pp0_stage0)
    begin
        if (((icmp_ln6_reg_489_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_phi_mux_icmp_ln97_phi_fu_152_p4 <= icmp_ln9_reg_518;
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_phi_mux_icmp_ln97_phi_fu_152_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_icmp_ln97_phi_fu_152_p4 <= icmp_ln9_reg_518;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten131_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten131_fu_68)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten131_load <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_indvar_flatten131_load <= indvar_flatten131_fu_68;
        end if; 
    end process;

    empty_6_fu_285_p1 <= k_mid2_fu_277_p3(4 - 1 downto 0);
    empty_fu_271_p2 <= (ap_phi_mux_icmp_ln78_phi_fu_141_p4 or and_ln6_fu_247_p2);
    i_3_fu_253_p3 <= 
        add_ln6_fu_227_p2 when (ap_phi_mux_icmp_ln78_phi_fu_141_p4(0) = '1') else 
        i_fu_72;
    icmp_ln11_fu_353_p2 <= "1" when (signed(zext_ln9_fu_349_p1) < signed(size_read_reg_484)) else "0";
    icmp_ln6_fu_204_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten131_load = ap_const_lv12_FFF) else "0";
    icmp_ln7_fu_384_p2 <= "1" when (select_ln7_1_fu_376_p3 = ap_const_lv10_100) else "0";
    icmp_ln9_fu_364_p2 <= "1" when (k_3_fu_358_p2 = ap_const_lv5_10) else "0";
    in1_address0 <= zext_ln12_1_fu_325_p1(8 - 1 downto 0);
    in1_ce0 <= in1_ce0_local;

    in1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in1_ce0_local <= ap_const_logic_1;
        else 
            in1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in2_address0 <= zext_ln12_2_fu_344_p1(8 - 1 downto 0);
    in2_ce0 <= in2_ce0_local;

    in2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in2_ce0_local <= ap_const_logic_1;
        else 
            in2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    j_3_fu_289_p3 <= 
        add_ln7_fu_265_p2 when (and_ln6_fu_247_p2(0) = '1') else 
        select_ln6_fu_233_p3;
    k_3_fu_358_p2 <= std_logic_vector(unsigned(k_mid2_fu_277_p3) + unsigned(ap_const_lv5_1));
    k_mid2_fu_277_p3 <= 
        ap_const_lv5_0 when (empty_fu_271_p2(0) = '1') else 
        k_fu_84;
    out_r_address0 <= zext_ln15_1_fu_420_p1(8 - 1 downto 0);
    out_r_ce0 <= out_r_ce0_local;

    out_r_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            out_r_ce0_local <= ap_const_logic_1;
        else 
            out_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    out_r_d0 <= sum_1_fu_429_p3;
    out_r_we0 <= out_r_we0_local;

    out_r_we0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001, icmp_ln9_reg_518_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln9_reg_518_pp0_iter3_reg = ap_const_lv1_1))) then 
            out_r_we0_local <= ap_const_logic_1;
        else 
            out_r_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln6_fu_233_p3 <= 
        ap_const_lv5_0 when (ap_phi_mux_icmp_ln78_phi_fu_141_p4(0) = '1') else 
        j_fu_80;
    select_ln7_1_fu_376_p3 <= 
        ap_const_lv10_1 when (ap_phi_mux_icmp_ln78_phi_fu_141_p4(0) = '1') else 
        add_ln7_1_fu_370_p2;
    sum_1_fu_429_p3 <= 
        sum_4_fu_424_p2 when (icmp_ln11_reg_513_pp0_iter3_reg(0) = '1') else 
        sum_mid2_fu_413_p3;
    sum_4_fu_424_p2 <= std_logic_vector(unsigned(mul_ln12_reg_538) + unsigned(sum_mid2_fu_413_p3));
    sum_mid2_fu_413_p3 <= 
        ap_const_lv32_0 when (empty_reg_493_pp0_iter3_reg(0) = '1') else 
        sum_fu_88;
    tmp_1_fu_330_p3 <= (empty_6_fu_285_p1 & ap_const_lv4_0);
    tmp_fu_297_p3 <= (trunc_ln7_fu_261_p1 & ap_const_lv4_0);
    trunc_ln7_fu_261_p1 <= i_3_fu_253_p3(4 - 1 downto 0);
    xor_ln6_fu_241_p2 <= (ap_phi_mux_icmp_ln78_phi_fu_141_p4 xor ap_const_lv1_1);
    zext_ln12_1_fu_325_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln12_fu_319_p2),64));
    zext_ln12_2_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln12_1_fu_338_p2),64));
    zext_ln12_fu_315_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_mid2_fu_277_p3),8));
    zext_ln15_1_fu_420_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln15_reg_498_pp0_iter3_reg),64));
    zext_ln15_fu_305_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_3_fu_289_p3),8));
    zext_ln9_fu_349_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_mid2_fu_277_p3),32));
end behav;
