[hls]
relative_roots=/home/nhanenten/Desktop/HW_SW/Lab3/Lab3B_HLS
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=matmul/VITIS_LOOP_7_2  
syn.directive.loop_flatten=matmul/VITIS_LOOP_6_1  


