// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matmul_matmul,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=2052,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=728,HLS_SYN_LUT=2331,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module matmul (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in1_address0,
        in1_ce0,
        in1_q0,
        in1_address1,
        in1_ce1,
        in1_q1,
        in2_address0,
        in2_ce0,
        in2_q0,
        in2_address1,
        in2_ce1,
        in2_q1,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        size
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] in1_address0;
output   in1_ce0;
input  [31:0] in1_q0;
output  [7:0] in1_address1;
output   in1_ce1;
input  [31:0] in1_q1;
output  [7:0] in2_address0;
output   in2_ce0;
input  [31:0] in2_q0;
output  [7:0] in2_address1;
output   in2_ce1;
input  [31:0] in2_q1;
output  [7:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [31:0] out_r_d0;
input  [31:0] size;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [0:0] icmp_ln6_fu_1230_p2;
reg    ap_condition_exit_pp0_iter0_stage7;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_11001;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_11001;
wire    ap_block_pp0_stage7_11001;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] grp_fu_477_p2;
reg   [31:0] reg_509;
wire   [31:0] grp_fu_483_p2;
reg   [31:0] reg_513;
wire   [0:0] icmp_ln10_fu_517_p2;
reg   [0:0] icmp_ln10_reg_1344;
wire   [0:0] icmp_ln10_1_fu_533_p2;
reg   [0:0] icmp_ln10_1_reg_1349;
wire   [0:0] icmp_ln10_2_fu_539_p2;
reg   [0:0] icmp_ln10_2_reg_1354;
wire   [0:0] icmp_ln10_3_fu_555_p2;
reg   [0:0] icmp_ln10_3_reg_1359;
wire   [0:0] icmp_ln10_4_fu_561_p2;
reg   [0:0] icmp_ln10_4_reg_1364;
wire   [0:0] icmp_ln10_5_fu_567_p2;
reg   [0:0] icmp_ln10_5_reg_1369;
wire   [0:0] icmp_ln10_6_fu_573_p2;
reg   [0:0] icmp_ln10_6_reg_1374;
wire   [0:0] icmp_ln10_7_fu_589_p2;
reg   [0:0] icmp_ln10_7_reg_1379;
wire   [0:0] icmp_ln10_8_fu_595_p2;
reg   [0:0] icmp_ln10_8_reg_1384;
wire   [0:0] icmp_ln10_9_fu_601_p2;
reg   [0:0] icmp_ln10_9_reg_1389;
wire   [0:0] icmp_ln10_10_fu_607_p2;
reg   [0:0] icmp_ln10_10_reg_1394;
wire   [0:0] icmp_ln10_11_fu_613_p2;
reg   [0:0] icmp_ln10_11_reg_1399;
wire   [0:0] icmp_ln10_12_fu_619_p2;
reg   [0:0] icmp_ln10_12_reg_1404;
reg   [0:0] icmp_ln10_12_reg_1404_pp0_iter1_reg;
wire   [0:0] icmp_ln10_13_fu_625_p2;
reg   [0:0] icmp_ln10_13_reg_1409;
reg   [0:0] icmp_ln10_13_reg_1409_pp0_iter1_reg;
wire   [0:0] icmp_ln10_14_fu_631_p2;
reg   [0:0] icmp_ln10_14_reg_1414;
reg   [0:0] icmp_ln10_14_reg_1414_pp0_iter1_reg;
wire   [0:0] icmp_ln10_15_fu_647_p2;
reg   [0:0] icmp_ln10_15_reg_1419;
reg   [0:0] icmp_ln10_15_reg_1419_pp0_iter1_reg;
wire   [4:0] select_ln6_fu_680_p3;
reg   [4:0] select_ln6_reg_1424;
wire   [3:0] trunc_ln11_fu_696_p1;
reg   [3:0] trunc_ln11_reg_1433;
wire   [7:0] tmp_fu_700_p3;
reg   [7:0] tmp_reg_1451;
wire   [5:0] zext_ln11_18_fu_731_p1;
reg   [5:0] zext_ln11_18_reg_1466;
reg   [0:0] bit_sel_reg_1481;
wire   [3:0] trunc_ln11_1_fu_754_p1;
reg   [3:0] trunc_ln11_1_reg_1486;
wire   [6:0] zext_ln11_17_fu_787_p1;
reg   [6:0] zext_ln11_17_reg_1501;
wire  signed [5:0] tmp_16_cast_fu_790_p3;
reg  signed [5:0] tmp_16_cast_reg_1507;
wire  signed [6:0] tmp_17_cast_fu_837_p3;
reg  signed [6:0] tmp_17_cast_reg_1533;
wire  signed [6:0] add_ln11_2_fu_849_p2;
reg  signed [6:0] add_ln11_2_reg_1543;
wire   [7:0] zext_ln11_16_fu_883_p1;
reg   [7:0] zext_ln11_16_reg_1563;
wire   [31:0] sum_3_fu_918_p3;
reg   [31:0] sum_3_reg_1580;
wire   [31:0] sum_7_fu_988_p3;
reg   [31:0] sum_7_reg_1606;
wire   [7:0] add_ln14_fu_1041_p2;
reg   [7:0] add_ln14_reg_1632;
wire   [31:0] sum_11_fu_1062_p3;
reg   [31:0] sum_11_reg_1637;
wire   [31:0] sum_15_fu_1126_p3;
reg   [31:0] sum_15_reg_1663;
wire   [31:0] sum_19_fu_1206_p3;
reg   [31:0] sum_19_reg_1689;
wire   [0:0] icmp_ln7_fu_1224_p2;
reg   [0:0] icmp_ln7_reg_1695;
reg   [0:0] icmp_ln6_reg_1700;
wire   [31:0] sum_23_fu_1263_p3;
reg   [31:0] sum_23_reg_1704;
wire   [31:0] sum_27_fu_1287_p3;
reg   [31:0] sum_27_reg_1710;
wire    ap_block_pp0_stage2_subdone;
reg   [0:0] ap_phi_mux_icmp_ln74_phi_fu_470_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln11_fu_708_p1;
wire   [63:0] zext_ln11_1_fu_721_p1;
wire   [63:0] zext_ln7_fu_726_p1;
wire   [63:0] zext_ln11_19_fu_741_p1;
wire   [63:0] zext_ln11_2_fu_770_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln11_3_fu_782_p1;
wire   [63:0] zext_ln11_20_fu_797_p1;
wire   [63:0] zext_ln11_21_fu_808_p1;
wire   [63:0] zext_ln11_4_fu_820_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln11_5_fu_832_p1;
wire   [63:0] zext_ln11_22_fu_844_p1;
wire   [63:0] zext_ln11_23_fu_854_p1;
wire   [63:0] zext_ln11_6_fu_866_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln11_7_fu_878_p1;
wire   [63:0] zext_ln11_24_fu_889_p1;
wire   [63:0] zext_ln11_25_fu_900_p1;
wire   [63:0] zext_ln11_8_fu_932_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] zext_ln11_9_fu_944_p1;
wire   [63:0] zext_ln11_26_fu_956_p1;
wire   [63:0] zext_ln11_27_fu_966_p1;
wire   [63:0] zext_ln11_10_fu_1002_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] zext_ln11_11_fu_1014_p1;
wire   [63:0] zext_ln11_28_fu_1026_p1;
wire   [63:0] zext_ln11_29_fu_1036_p1;
wire   [63:0] zext_ln11_12_fu_1076_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] zext_ln11_13_fu_1088_p1;
wire   [63:0] zext_ln11_30_fu_1096_p1;
wire   [63:0] zext_ln11_31_fu_1104_p1;
wire   [63:0] zext_ln11_14_fu_1143_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] zext_ln11_15_fu_1155_p1;
wire   [63:0] zext_ln11_32_fu_1163_p1;
wire   [63:0] zext_ln11_33_fu_1184_p1;
wire   [63:0] zext_ln14_fu_1294_p1;
reg   [7:0] indvar_flatten1_fu_162;
wire   [7:0] add_ln6_1_fu_1218_p2;
reg   [4:0] i_fu_166;
wire   [4:0] i_3_fu_688_p3;
reg   [4:0] ap_sig_allocacmp_i_1;
reg   [4:0] j_fu_170;
wire   [4:0] j_3_fu_1213_p2;
reg   [4:0] ap_sig_allocacmp_j_1;
reg    in1_ce1_local;
reg   [7:0] in1_address1_local;
reg    in1_ce0_local;
reg   [7:0] in1_address0_local;
reg    in2_ce1_local;
reg   [7:0] in2_address1_local;
reg    in2_ce0_local;
reg   [7:0] in2_address0_local;
reg    out_r_we0_local;
wire   [31:0] sum_31_fu_1315_p3;
reg    out_r_ce0_local;
wire   [30:0] tmp_16_fu_523_p4;
wire   [29:0] tmp_17_fu_545_p4;
wire   [28:0] tmp_18_fu_579_p4;
wire   [27:0] tmp_19_fu_637_p4;
wire   [4:0] add_ln6_fu_674_p2;
wire   [7:0] tmp_1_fu_713_p3;
wire   [5:0] add_ln11_fu_735_p2;
wire   [7:0] tmp_2_fu_763_p3;
wire   [7:0] tmp_3_fu_775_p3;
wire   [6:0] add_ln11_1_fu_802_p2;
wire   [7:0] tmp_4_fu_813_p3;
wire   [7:0] tmp_5_fu_825_p3;
wire   [7:0] tmp_6_fu_859_p3;
wire   [7:0] tmp_7_fu_871_p3;
wire  signed [6:0] sext_ln11_fu_886_p1;
wire   [7:0] add_ln11_3_fu_894_p2;
wire   [31:0] sum_1_fu_905_p3;
wire   [31:0] sum_2_fu_912_p2;
wire   [7:0] tmp_8_fu_925_p3;
wire   [7:0] tmp_9_fu_937_p3;
wire   [7:0] tmp_19_cast_fu_949_p3;
wire   [7:0] add_ln11_4_fu_961_p2;
wire   [31:0] sum_4_fu_971_p2;
wire   [31:0] sum_5_fu_976_p3;
wire   [31:0] sum_6_fu_982_p2;
wire   [7:0] tmp_s_fu_995_p3;
wire   [7:0] tmp_10_fu_1007_p3;
wire   [7:0] tmp_20_cast_fu_1019_p3;
wire   [7:0] add_ln11_5_fu_1031_p2;
wire   [31:0] sum_8_fu_1045_p2;
wire   [31:0] sum_9_fu_1050_p3;
wire   [31:0] sum_10_fu_1056_p2;
wire   [7:0] tmp_11_fu_1069_p3;
wire   [7:0] tmp_12_fu_1081_p3;
wire  signed [7:0] sext_ln11_1_fu_1093_p1;
wire  signed [7:0] sext_ln11_2_fu_1101_p1;
wire   [31:0] sum_12_fu_1109_p2;
wire   [31:0] sum_13_fu_1114_p3;
wire   [31:0] sum_14_fu_1120_p2;
wire   [7:0] tmp_13_fu_1136_p3;
wire   [7:0] tmp_14_fu_1148_p3;
wire  signed [7:0] sext_ln11_3_fu_1160_p1;
wire   [0:0] xor_ln11_fu_1168_p2;
wire   [4:0] add_ln11_7_fu_1173_p3;
wire  signed [7:0] sext_ln11_4_fu_1180_p1;
wire   [31:0] sum_16_fu_1189_p2;
wire   [31:0] sum_17_fu_1194_p3;
wire   [31:0] sum_18_fu_1200_p2;
wire   [31:0] sum_20_fu_1246_p2;
wire   [31:0] sum_21_fu_1251_p3;
wire   [31:0] sum_22_fu_1257_p2;
wire   [31:0] sum_24_fu_1270_p2;
wire   [31:0] sum_25_fu_1275_p3;
wire   [31:0] sum_26_fu_1281_p2;
wire   [31:0] sum_28_fu_1298_p2;
wire   [31:0] sum_29_fu_1303_p3;
wire   [31:0] sum_30_fu_1309_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage2;
reg    ap_idle_pp0_0to0;
reg   [7:0] ap_NS_fsm;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_1126;
reg    ap_condition_460;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 indvar_flatten1_fu_162 = 8'd0;
#0 i_fu_166 = 5'd0;
#0 j_fu_170 = 5'd0;
#0 ap_done_reg = 1'b0;
end

matmul_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(in2_q1),
    .din1(in1_q1),
    .ce(1'b1),
    .dout(grp_fu_477_p2)
);

matmul_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(in2_q0),
    .din1(in1_q0),
    .ce(1'b1),
    .dout(grp_fu_483_p2)
);

matmul_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage7),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_condition_exit_pp0_iter1_stage2) & (ap_idle_pp0_0to0 == 1'b1)))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_460)) begin
        i_fu_166 <= i_3_fu_688_p3;
    end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
    indvar_flatten1_fu_162 <= 8'd0;
end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
    indvar_flatten1_fu_162 <= add_ln6_1_fu_1218_p2;
end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
    j_fu_170 <= 5'd0;
end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
    j_fu_170 <= j_3_fu_1213_p2;
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln11_2_reg_1543 <= add_ln11_2_fu_849_p2;
        tmp_17_cast_reg_1533[4 : 0] <= tmp_17_cast_fu_837_p3[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        add_ln14_reg_1632 <= add_ln14_fu_1041_p2;
        sum_11_reg_1637 <= sum_11_fu_1062_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bit_sel_reg_1481 <= select_ln6_fu_680_p3[5'd4];
        icmp_ln10_10_reg_1394 <= icmp_ln10_10_fu_607_p2;
        icmp_ln10_11_reg_1399 <= icmp_ln10_11_fu_613_p2;
        icmp_ln10_12_reg_1404 <= icmp_ln10_12_fu_619_p2;
        icmp_ln10_12_reg_1404_pp0_iter1_reg <= icmp_ln10_12_reg_1404;
        icmp_ln10_13_reg_1409 <= icmp_ln10_13_fu_625_p2;
        icmp_ln10_13_reg_1409_pp0_iter1_reg <= icmp_ln10_13_reg_1409;
        icmp_ln10_14_reg_1414 <= icmp_ln10_14_fu_631_p2;
        icmp_ln10_14_reg_1414_pp0_iter1_reg <= icmp_ln10_14_reg_1414;
        icmp_ln10_15_reg_1419 <= icmp_ln10_15_fu_647_p2;
        icmp_ln10_15_reg_1419_pp0_iter1_reg <= icmp_ln10_15_reg_1419;
        icmp_ln10_1_reg_1349 <= icmp_ln10_1_fu_533_p2;
        icmp_ln10_2_reg_1354 <= icmp_ln10_2_fu_539_p2;
        icmp_ln10_3_reg_1359 <= icmp_ln10_3_fu_555_p2;
        icmp_ln10_4_reg_1364 <= icmp_ln10_4_fu_561_p2;
        icmp_ln10_5_reg_1369 <= icmp_ln10_5_fu_567_p2;
        icmp_ln10_6_reg_1374 <= icmp_ln10_6_fu_573_p2;
        icmp_ln10_7_reg_1379 <= icmp_ln10_7_fu_589_p2;
        icmp_ln10_8_reg_1384 <= icmp_ln10_8_fu_595_p2;
        icmp_ln10_9_reg_1389 <= icmp_ln10_9_fu_601_p2;
        icmp_ln10_reg_1344 <= icmp_ln10_fu_517_p2;
        select_ln6_reg_1424 <= select_ln6_fu_680_p3;
        sum_23_reg_1704 <= sum_23_fu_1263_p3;
        tmp_reg_1451[7 : 4] <= tmp_fu_700_p3[7 : 4];
        trunc_ln11_1_reg_1486 <= trunc_ln11_1_fu_754_p1;
        trunc_ln11_reg_1433 <= trunc_ln11_fu_696_p1;
        zext_ln11_18_reg_1466[4 : 0] <= zext_ln11_18_fu_731_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        icmp_ln6_reg_1700 <= icmp_ln6_fu_1230_p2;
        sum_19_reg_1689 <= sum_19_fu_1206_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        icmp_ln7_reg_1695 <= icmp_ln7_fu_1224_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_509 <= grp_fu_477_p2;
        reg_513 <= grp_fu_483_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        sum_15_reg_1663 <= sum_15_fu_1126_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sum_27_reg_1710 <= sum_27_fu_1287_p3;
        tmp_16_cast_reg_1507[4 : 0] <= tmp_16_cast_fu_790_p3[4 : 0];
        zext_ln11_17_reg_1501[4 : 0] <= zext_ln11_17_fu_787_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        sum_3_reg_1580 <= sum_3_fu_918_p3;
        zext_ln11_16_reg_1563[4 : 0] <= zext_ln11_16_fu_883_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        sum_7_reg_1606 <= sum_7_fu_988_p3;
    end
end

always @ (*) begin
    if (((icmp_ln6_fu_1230_p2 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (icmp_ln6_reg_1700 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter1_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_1126)) begin
            ap_phi_mux_icmp_ln74_phi_fu_470_p4 = icmp_ln7_reg_1695;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln74_phi_fu_470_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln74_phi_fu_470_p4 = icmp_ln7_reg_1695;
        end
    end else begin
        ap_phi_mux_icmp_ln74_phi_fu_470_p4 = icmp_ln7_reg_1695;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_166;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_170;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        in1_address0_local = zext_ln11_15_fu_1155_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        in1_address0_local = zext_ln11_13_fu_1088_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        in1_address0_local = zext_ln11_11_fu_1014_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        in1_address0_local = zext_ln11_9_fu_944_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        in1_address0_local = zext_ln11_7_fu_878_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        in1_address0_local = zext_ln11_5_fu_832_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in1_address0_local = zext_ln11_3_fu_782_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in1_address0_local = zext_ln11_1_fu_721_p1;
    end else begin
        in1_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        in1_address1_local = zext_ln11_14_fu_1143_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        in1_address1_local = zext_ln11_12_fu_1076_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        in1_address1_local = zext_ln11_10_fu_1002_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        in1_address1_local = zext_ln11_8_fu_932_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        in1_address1_local = zext_ln11_6_fu_866_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        in1_address1_local = zext_ln11_4_fu_820_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in1_address1_local = zext_ln11_2_fu_770_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in1_address1_local = zext_ln11_fu_708_p1;
    end else begin
        in1_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        in1_ce0_local = 1'b1;
    end else begin
        in1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        in1_ce1_local = 1'b1;
    end else begin
        in1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        in2_address0_local = zext_ln11_33_fu_1184_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        in2_address0_local = zext_ln11_31_fu_1104_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        in2_address0_local = zext_ln11_29_fu_1036_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        in2_address0_local = zext_ln11_27_fu_966_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        in2_address0_local = zext_ln11_25_fu_900_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        in2_address0_local = zext_ln11_23_fu_854_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in2_address0_local = zext_ln11_21_fu_808_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in2_address0_local = zext_ln11_19_fu_741_p1;
    end else begin
        in2_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        in2_address1_local = zext_ln11_32_fu_1163_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        in2_address1_local = zext_ln11_30_fu_1096_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        in2_address1_local = zext_ln11_28_fu_1026_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        in2_address1_local = zext_ln11_26_fu_956_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        in2_address1_local = zext_ln11_24_fu_889_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        in2_address1_local = zext_ln11_22_fu_844_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in2_address1_local = zext_ln11_20_fu_797_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in2_address1_local = zext_ln7_fu_726_p1;
    end else begin
        in2_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        in2_ce0_local = 1'b1;
    end else begin
        in2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        in2_ce1_local = 1'b1;
    end else begin
        in2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        out_r_ce0_local = 1'b1;
    end else begin
        out_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        out_r_we0_local = 1'b1;
    end else begin
        out_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter1_stage2) & (ap_idle_pp0_0to0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln11_1_fu_802_p2 = (zext_ln11_17_fu_787_p1 + 7'd48);

assign add_ln11_2_fu_849_p2 = ($signed(zext_ln11_17_reg_1501) + $signed(7'd80));

assign add_ln11_3_fu_894_p2 = (zext_ln11_16_fu_883_p1 + 8'd112);

assign add_ln11_4_fu_961_p2 = ($signed(zext_ln11_16_reg_1563) + $signed(8'd144));

assign add_ln11_5_fu_1031_p2 = ($signed(zext_ln11_16_reg_1563) + $signed(8'd176));

assign add_ln11_7_fu_1173_p3 = {{xor_ln11_fu_1168_p2}, {trunc_ln11_1_reg_1486}};

assign add_ln11_fu_735_p2 = (zext_ln11_18_fu_731_p1 + 6'd16);

assign add_ln14_fu_1041_p2 = (tmp_reg_1451 + zext_ln11_16_reg_1563);

assign add_ln6_1_fu_1218_p2 = (indvar_flatten1_fu_162 + 8'd1);

assign add_ln6_fu_674_p2 = (ap_sig_allocacmp_i_1 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1126 = ((1'b0 == ap_block_pp0_stage0) & (icmp_ln6_reg_1700 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_460 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage7;

assign ap_ready = ap_ready_sig;

assign i_3_fu_688_p3 = ((ap_phi_mux_icmp_ln74_phi_fu_470_p4[0:0] == 1'b1) ? add_ln6_fu_674_p2 : ap_sig_allocacmp_i_1);

assign icmp_ln10_10_fu_607_p2 = (($signed(size) > $signed(32'd10)) ? 1'b1 : 1'b0);

assign icmp_ln10_11_fu_613_p2 = (($signed(size) > $signed(32'd11)) ? 1'b1 : 1'b0);

assign icmp_ln10_12_fu_619_p2 = (($signed(size) > $signed(32'd12)) ? 1'b1 : 1'b0);

assign icmp_ln10_13_fu_625_p2 = (($signed(size) > $signed(32'd13)) ? 1'b1 : 1'b0);

assign icmp_ln10_14_fu_631_p2 = (($signed(size) > $signed(32'd14)) ? 1'b1 : 1'b0);

assign icmp_ln10_15_fu_647_p2 = (($signed(tmp_19_fu_637_p4) > $signed(28'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_1_fu_533_p2 = (($signed(tmp_16_fu_523_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_2_fu_539_p2 = (($signed(size) > $signed(32'd2)) ? 1'b1 : 1'b0);

assign icmp_ln10_3_fu_555_p2 = (($signed(tmp_17_fu_545_p4) > $signed(30'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_4_fu_561_p2 = (($signed(size) > $signed(32'd4)) ? 1'b1 : 1'b0);

assign icmp_ln10_5_fu_567_p2 = (($signed(size) > $signed(32'd5)) ? 1'b1 : 1'b0);

assign icmp_ln10_6_fu_573_p2 = (($signed(size) > $signed(32'd6)) ? 1'b1 : 1'b0);

assign icmp_ln10_7_fu_589_p2 = (($signed(tmp_18_fu_579_p4) > $signed(29'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_8_fu_595_p2 = (($signed(size) > $signed(32'd8)) ? 1'b1 : 1'b0);

assign icmp_ln10_9_fu_601_p2 = (($signed(size) > $signed(32'd9)) ? 1'b1 : 1'b0);

assign icmp_ln10_fu_517_p2 = (($signed(size) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln6_fu_1230_p2 = ((indvar_flatten1_fu_162 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_1224_p2 = ((j_3_fu_1213_p2 == 5'd16) ? 1'b1 : 1'b0);

assign in1_address0 = in1_address0_local;

assign in1_address1 = in1_address1_local;

assign in1_ce0 = in1_ce0_local;

assign in1_ce1 = in1_ce1_local;

assign in2_address0 = in2_address0_local;

assign in2_address1 = in2_address1_local;

assign in2_ce0 = in2_ce0_local;

assign in2_ce1 = in2_ce1_local;

assign j_3_fu_1213_p2 = (select_ln6_reg_1424 + 5'd1);

assign out_r_address0 = zext_ln14_fu_1294_p1;

assign out_r_ce0 = out_r_ce0_local;

assign out_r_d0 = sum_31_fu_1315_p3;

assign out_r_we0 = out_r_we0_local;

assign select_ln6_fu_680_p3 = ((ap_phi_mux_icmp_ln74_phi_fu_470_p4[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_j_1);

assign sext_ln11_1_fu_1093_p1 = tmp_17_cast_reg_1533;

assign sext_ln11_2_fu_1101_p1 = add_ln11_2_reg_1543;

assign sext_ln11_3_fu_1160_p1 = tmp_16_cast_reg_1507;

assign sext_ln11_4_fu_1180_p1 = $signed(add_ln11_7_fu_1173_p3);

assign sext_ln11_fu_886_p1 = tmp_16_cast_reg_1507;

assign sum_10_fu_1056_p2 = (reg_513 + sum_9_fu_1050_p3);

assign sum_11_fu_1062_p3 = ((icmp_ln10_5_reg_1369[0:0] == 1'b1) ? sum_10_fu_1056_p2 : sum_9_fu_1050_p3);

assign sum_12_fu_1109_p2 = (reg_509 + sum_11_reg_1637);

assign sum_13_fu_1114_p3 = ((icmp_ln10_6_reg_1374[0:0] == 1'b1) ? sum_12_fu_1109_p2 : sum_11_reg_1637);

assign sum_14_fu_1120_p2 = (reg_513 + sum_13_fu_1114_p3);

assign sum_15_fu_1126_p3 = ((icmp_ln10_7_reg_1379[0:0] == 1'b1) ? sum_14_fu_1120_p2 : sum_13_fu_1114_p3);

assign sum_16_fu_1189_p2 = (reg_509 + sum_15_reg_1663);

assign sum_17_fu_1194_p3 = ((icmp_ln10_8_reg_1384[0:0] == 1'b1) ? sum_16_fu_1189_p2 : sum_15_reg_1663);

assign sum_18_fu_1200_p2 = (reg_513 + sum_17_fu_1194_p3);

assign sum_19_fu_1206_p3 = ((icmp_ln10_9_reg_1389[0:0] == 1'b1) ? sum_18_fu_1200_p2 : sum_17_fu_1194_p3);

assign sum_1_fu_905_p3 = ((icmp_ln10_reg_1344[0:0] == 1'b1) ? reg_509 : 32'd0);

assign sum_20_fu_1246_p2 = (reg_509 + sum_19_reg_1689);

assign sum_21_fu_1251_p3 = ((icmp_ln10_10_reg_1394[0:0] == 1'b1) ? sum_20_fu_1246_p2 : sum_19_reg_1689);

assign sum_22_fu_1257_p2 = (reg_513 + sum_21_fu_1251_p3);

assign sum_23_fu_1263_p3 = ((icmp_ln10_11_reg_1399[0:0] == 1'b1) ? sum_22_fu_1257_p2 : sum_21_fu_1251_p3);

assign sum_24_fu_1270_p2 = (reg_509 + sum_23_reg_1704);

assign sum_25_fu_1275_p3 = ((icmp_ln10_12_reg_1404_pp0_iter1_reg[0:0] == 1'b1) ? sum_24_fu_1270_p2 : sum_23_reg_1704);

assign sum_26_fu_1281_p2 = (reg_513 + sum_25_fu_1275_p3);

assign sum_27_fu_1287_p3 = ((icmp_ln10_13_reg_1409_pp0_iter1_reg[0:0] == 1'b1) ? sum_26_fu_1281_p2 : sum_25_fu_1275_p3);

assign sum_28_fu_1298_p2 = (reg_509 + sum_27_reg_1710);

assign sum_29_fu_1303_p3 = ((icmp_ln10_14_reg_1414_pp0_iter1_reg[0:0] == 1'b1) ? sum_28_fu_1298_p2 : sum_27_reg_1710);

assign sum_2_fu_912_p2 = (reg_513 + sum_1_fu_905_p3);

assign sum_30_fu_1309_p2 = (reg_513 + sum_29_fu_1303_p3);

assign sum_31_fu_1315_p3 = ((icmp_ln10_15_reg_1419_pp0_iter1_reg[0:0] == 1'b1) ? sum_30_fu_1309_p2 : sum_29_fu_1303_p3);

assign sum_3_fu_918_p3 = ((icmp_ln10_1_reg_1349[0:0] == 1'b1) ? sum_2_fu_912_p2 : sum_1_fu_905_p3);

assign sum_4_fu_971_p2 = (reg_509 + sum_3_reg_1580);

assign sum_5_fu_976_p3 = ((icmp_ln10_2_reg_1354[0:0] == 1'b1) ? sum_4_fu_971_p2 : sum_3_reg_1580);

assign sum_6_fu_982_p2 = (reg_513 + sum_5_fu_976_p3);

assign sum_7_fu_988_p3 = ((icmp_ln10_3_reg_1359[0:0] == 1'b1) ? sum_6_fu_982_p2 : sum_5_fu_976_p3);

assign sum_8_fu_1045_p2 = (reg_509 + sum_7_reg_1606);

assign sum_9_fu_1050_p3 = ((icmp_ln10_4_reg_1364[0:0] == 1'b1) ? sum_8_fu_1045_p2 : sum_7_reg_1606);

assign tmp_10_fu_1007_p3 = {{trunc_ln11_reg_1433}, {4'd11}};

assign tmp_11_fu_1069_p3 = {{trunc_ln11_reg_1433}, {4'd12}};

assign tmp_12_fu_1081_p3 = {{trunc_ln11_reg_1433}, {4'd13}};

assign tmp_13_fu_1136_p3 = {{trunc_ln11_reg_1433}, {4'd14}};

assign tmp_14_fu_1148_p3 = {{trunc_ln11_reg_1433}, {4'd15}};

assign tmp_16_cast_fu_790_p3 = {{1'd1}, {select_ln6_reg_1424}};

assign tmp_16_fu_523_p4 = {{size[31:1]}};

assign tmp_17_cast_fu_837_p3 = {{1'd1}, {zext_ln11_18_reg_1466}};

assign tmp_17_fu_545_p4 = {{size[31:2]}};

assign tmp_18_fu_579_p4 = {{size[31:3]}};

assign tmp_19_cast_fu_949_p3 = {{1'd1}, {zext_ln11_17_reg_1501}};

assign tmp_19_fu_637_p4 = {{size[31:4]}};

assign tmp_1_fu_713_p3 = {{trunc_ln11_fu_696_p1}, {4'd1}};

assign tmp_20_cast_fu_1019_p3 = {{3'd5}, {select_ln6_reg_1424}};

assign tmp_2_fu_763_p3 = {{trunc_ln11_reg_1433}, {4'd2}};

assign tmp_3_fu_775_p3 = {{trunc_ln11_reg_1433}, {4'd3}};

assign tmp_4_fu_813_p3 = {{trunc_ln11_reg_1433}, {4'd4}};

assign tmp_5_fu_825_p3 = {{trunc_ln11_reg_1433}, {4'd5}};

assign tmp_6_fu_859_p3 = {{trunc_ln11_reg_1433}, {4'd6}};

assign tmp_7_fu_871_p3 = {{trunc_ln11_reg_1433}, {4'd7}};

assign tmp_8_fu_925_p3 = {{trunc_ln11_reg_1433}, {4'd8}};

assign tmp_9_fu_937_p3 = {{trunc_ln11_reg_1433}, {4'd9}};

assign tmp_fu_700_p3 = {{trunc_ln11_fu_696_p1}, {4'd0}};

assign tmp_s_fu_995_p3 = {{trunc_ln11_reg_1433}, {4'd10}};

assign trunc_ln11_1_fu_754_p1 = select_ln6_fu_680_p3[3:0];

assign trunc_ln11_fu_696_p1 = i_3_fu_688_p3[3:0];

assign xor_ln11_fu_1168_p2 = (bit_sel_reg_1481 ^ 1'd1);

assign zext_ln11_10_fu_1002_p1 = tmp_s_fu_995_p3;

assign zext_ln11_11_fu_1014_p1 = tmp_10_fu_1007_p3;

assign zext_ln11_12_fu_1076_p1 = tmp_11_fu_1069_p3;

assign zext_ln11_13_fu_1088_p1 = tmp_12_fu_1081_p3;

assign zext_ln11_14_fu_1143_p1 = tmp_13_fu_1136_p3;

assign zext_ln11_15_fu_1155_p1 = tmp_14_fu_1148_p3;

assign zext_ln11_16_fu_883_p1 = select_ln6_reg_1424;

assign zext_ln11_17_fu_787_p1 = select_ln6_reg_1424;

assign zext_ln11_18_fu_731_p1 = select_ln6_fu_680_p3;

assign zext_ln11_19_fu_741_p1 = add_ln11_fu_735_p2;

assign zext_ln11_1_fu_721_p1 = tmp_1_fu_713_p3;

assign zext_ln11_20_fu_797_p1 = $unsigned(tmp_16_cast_fu_790_p3);

assign zext_ln11_21_fu_808_p1 = add_ln11_1_fu_802_p2;

assign zext_ln11_22_fu_844_p1 = $unsigned(tmp_17_cast_fu_837_p3);

assign zext_ln11_23_fu_854_p1 = $unsigned(add_ln11_2_fu_849_p2);

assign zext_ln11_24_fu_889_p1 = $unsigned(sext_ln11_fu_886_p1);

assign zext_ln11_25_fu_900_p1 = add_ln11_3_fu_894_p2;

assign zext_ln11_26_fu_956_p1 = tmp_19_cast_fu_949_p3;

assign zext_ln11_27_fu_966_p1 = add_ln11_4_fu_961_p2;

assign zext_ln11_28_fu_1026_p1 = tmp_20_cast_fu_1019_p3;

assign zext_ln11_29_fu_1036_p1 = add_ln11_5_fu_1031_p2;

assign zext_ln11_2_fu_770_p1 = tmp_2_fu_763_p3;

assign zext_ln11_30_fu_1096_p1 = $unsigned(sext_ln11_1_fu_1093_p1);

assign zext_ln11_31_fu_1104_p1 = $unsigned(sext_ln11_2_fu_1101_p1);

assign zext_ln11_32_fu_1163_p1 = $unsigned(sext_ln11_3_fu_1160_p1);

assign zext_ln11_33_fu_1184_p1 = $unsigned(sext_ln11_4_fu_1180_p1);

assign zext_ln11_3_fu_782_p1 = tmp_3_fu_775_p3;

assign zext_ln11_4_fu_820_p1 = tmp_4_fu_813_p3;

assign zext_ln11_5_fu_832_p1 = tmp_5_fu_825_p3;

assign zext_ln11_6_fu_866_p1 = tmp_6_fu_859_p3;

assign zext_ln11_7_fu_878_p1 = tmp_7_fu_871_p3;

assign zext_ln11_8_fu_932_p1 = tmp_8_fu_925_p3;

assign zext_ln11_9_fu_944_p1 = tmp_9_fu_937_p3;

assign zext_ln11_fu_708_p1 = tmp_fu_700_p3;

assign zext_ln14_fu_1294_p1 = add_ln14_reg_1632;

assign zext_ln7_fu_726_p1 = select_ln6_fu_680_p3;

always @ (posedge ap_clk) begin
    tmp_reg_1451[3:0] <= 4'b0000;
    zext_ln11_18_reg_1466[5] <= 1'b0;
    zext_ln11_17_reg_1501[6:5] <= 2'b00;
    tmp_16_cast_reg_1507[5] <= 1'b1;
    tmp_17_cast_reg_1533[6:5] <= 2'b10;
    zext_ln11_16_reg_1563[7:5] <= 3'b000;
end

endmodule //matmul
