// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matmul_matmul,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=4101,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=645,HLS_SYN_LUT=641,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module matmul (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in1_address0,
        in1_ce0,
        in1_q0,
        in2_address0,
        in2_ce0,
        in2_q0,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        size
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] in1_address0;
output   in1_ce0;
input  [31:0] in1_q0;
output  [7:0] in2_address0;
output   in2_ce0;
input  [31:0] in2_q0;
output  [7:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [31:0] out_r_d0;
input  [31:0] size;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln6_fu_204_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg;
wire    ap_block_pp0_stage0_11001;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg;
reg    ap_loop_exit_ready_delayed;
reg   [31:0] size_read_reg_484;
reg   [0:0] icmp_ln6_reg_489;
reg   [0:0] icmp_ln6_reg_489_pp0_iter1_reg;
wire   [0:0] empty_fu_271_p2;
reg   [0:0] empty_reg_493;
reg   [0:0] empty_reg_493_pp0_iter2_reg;
reg   [0:0] empty_reg_493_pp0_iter3_reg;
wire   [7:0] add_ln15_fu_309_p2;
reg   [7:0] add_ln15_reg_498;
reg   [7:0] add_ln15_reg_498_pp0_iter2_reg;
reg   [7:0] add_ln15_reg_498_pp0_iter3_reg;
wire   [0:0] icmp_ln11_fu_353_p2;
reg   [0:0] icmp_ln11_reg_513;
reg   [0:0] icmp_ln11_reg_513_pp0_iter2_reg;
reg   [0:0] icmp_ln11_reg_513_pp0_iter3_reg;
wire   [0:0] icmp_ln9_fu_364_p2;
reg   [0:0] icmp_ln9_reg_518;
reg   [0:0] icmp_ln9_reg_518_pp0_iter2_reg;
reg   [0:0] icmp_ln9_reg_518_pp0_iter3_reg;
wire   [0:0] icmp_ln7_fu_384_p2;
reg   [0:0] icmp_ln7_reg_523;
wire   [31:0] grp_fu_159_p2;
reg   [31:0] mul_ln12_reg_538;
reg   [0:0] ap_phi_mux_icmp_ln78_phi_fu_141_p4;
wire    ap_loop_init;
reg    ap_loop_init_pp0_iter1_reg;
wire    ap_block_pp0_stage0;
reg   [0:0] ap_phi_mux_icmp_ln97_phi_fu_152_p4;
wire   [63:0] zext_ln12_1_fu_325_p1;
wire   [63:0] zext_ln12_2_fu_344_p1;
wire   [63:0] zext_ln15_1_fu_420_p1;
reg   [11:0] indvar_flatten131_fu_68;
wire   [11:0] add_ln6_1_fu_198_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten131_load;
reg   [4:0] i_fu_72;
wire   [4:0] i_3_fu_253_p3;
reg   [9:0] indvar_flatten3_fu_76;
wire   [9:0] select_ln7_1_fu_376_p3;
reg   [4:0] j_fu_80;
wire   [4:0] j_3_fu_289_p3;
reg   [4:0] k_fu_84;
wire   [4:0] k_3_fu_358_p2;
reg   [31:0] sum_fu_88;
wire   [31:0] sum_1_fu_429_p3;
reg    in1_ce0_local;
reg    in2_ce0_local;
reg    out_r_we0_local;
reg    out_r_ce0_local;
wire   [0:0] xor_ln6_fu_241_p2;
wire   [4:0] add_ln6_fu_227_p2;
wire   [4:0] select_ln6_fu_233_p3;
wire   [0:0] and_ln6_fu_247_p2;
wire   [4:0] k_mid2_fu_277_p3;
wire   [4:0] add_ln7_fu_265_p2;
wire   [3:0] trunc_ln7_fu_261_p1;
wire   [7:0] tmp_fu_297_p3;
wire   [7:0] zext_ln15_fu_305_p1;
wire   [7:0] zext_ln12_fu_315_p1;
wire   [7:0] add_ln12_fu_319_p2;
wire   [3:0] empty_6_fu_285_p1;
wire   [7:0] tmp_1_fu_330_p3;
wire   [7:0] add_ln12_1_fu_338_p2;
wire   [31:0] zext_ln9_fu_349_p1;
wire   [9:0] add_ln7_1_fu_370_p2;
wire   [31:0] sum_mid2_fu_413_p3;
wire   [31:0] sum_4_fu_424_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_164;
reg    ap_condition_162;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 indvar_flatten131_fu_68 = 12'd0;
#0 i_fu_72 = 5'd0;
#0 indvar_flatten3_fu_76 = 10'd0;
#0 j_fu_80 = 5'd0;
#0 k_fu_84 = 5'd0;
#0 sum_fu_88 = 32'd0;
#0 ap_done_reg = 1'b0;
end

matmul_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(in2_q0),
    .din1(in1_q0),
    .ce(1'b1),
    .dout(grp_fu_159_p2)
);

matmul_flow_control_loop_delay_pipe flow_control_loop_delay_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1),
    .ap_loop_exit_ready_delayed(ap_loop_exit_ready_delayed)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1))) begin
            i_fu_72 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_72 <= i_3_fu_253_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_164)) begin
        indvar_flatten131_fu_68 <= add_ln6_1_fu_198_p2;
    end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1))) begin
        indvar_flatten3_fu_76 <= 10'd0;
    end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        indvar_flatten3_fu_76 <= select_ln7_1_fu_376_p3;
    end
end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1))) begin
        j_fu_80 <= 5'd0;
    end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        j_fu_80 <= j_3_fu_289_p3;
    end
end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1))) begin
        k_fu_84 <= 5'd0;
    end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        k_fu_84 <= k_3_fu_358_p2;
    end
end
end

always @ (posedge ap_clk) begin
if ((1'b0 == ap_block_pp0_stage0_11001)) begin
    if ((1'b1 == ap_condition_162)) begin
        sum_fu_88 <= 32'd0;
    end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        sum_fu_88 <= sum_1_fu_429_p3;
    end
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln15_reg_498 <= add_ln15_fu_309_p2;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage0;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        empty_reg_493 <= empty_fu_271_p2;
        icmp_ln11_reg_513 <= icmp_ln11_fu_353_p2;
        icmp_ln6_reg_489 <= icmp_ln6_fu_204_p2;
        icmp_ln6_reg_489_pp0_iter1_reg <= icmp_ln6_reg_489;
        size_read_reg_484 <= size;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln15_reg_498_pp0_iter2_reg <= add_ln15_reg_498;
        add_ln15_reg_498_pp0_iter3_reg <= add_ln15_reg_498_pp0_iter2_reg;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        empty_reg_493_pp0_iter2_reg <= empty_reg_493;
        empty_reg_493_pp0_iter3_reg <= empty_reg_493_pp0_iter2_reg;
        icmp_ln11_reg_513_pp0_iter2_reg <= icmp_ln11_reg_513;
        icmp_ln11_reg_513_pp0_iter3_reg <= icmp_ln11_reg_513_pp0_iter2_reg;
        icmp_ln9_reg_518_pp0_iter2_reg <= icmp_ln9_reg_518;
        icmp_ln9_reg_518_pp0_iter3_reg <= icmp_ln9_reg_518_pp0_iter2_reg;
        mul_ln12_reg_538 <= grp_fu_159_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln7_reg_523 <= icmp_ln7_fu_384_p2;
        icmp_ln9_reg_518 <= icmp_ln9_fu_364_p2;
    end
end

always @ (*) begin
    if (((icmp_ln6_fu_204_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg))) begin
        ap_loop_exit_ready_delayed = 1'b1;
    end else begin
        ap_loop_exit_ready_delayed = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln6_reg_489_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_icmp_ln78_phi_fu_141_p4 = icmp_ln7_reg_523;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
        ap_phi_mux_icmp_ln78_phi_fu_141_p4 = 1'd0;
    end else begin
        ap_phi_mux_icmp_ln78_phi_fu_141_p4 = icmp_ln7_reg_523;
    end
end

always @ (*) begin
    if (((icmp_ln6_reg_489_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_icmp_ln97_phi_fu_152_p4 = icmp_ln9_reg_518;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
        ap_phi_mux_icmp_ln97_phi_fu_152_p4 = 1'd0;
    end else begin
        ap_phi_mux_icmp_ln97_phi_fu_152_p4 = icmp_ln9_reg_518;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten131_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten131_load = indvar_flatten131_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in1_ce0_local = 1'b1;
    end else begin
        in1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in2_ce0_local = 1'b1;
    end else begin
        in2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        out_r_ce0_local = 1'b1;
    end else begin
        out_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln9_reg_518_pp0_iter3_reg == 1'd1))) begin
        out_r_we0_local = 1'b1;
    end else begin
        out_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln12_1_fu_338_p2 = (tmp_1_fu_330_p3 + zext_ln15_fu_305_p1);

assign add_ln12_fu_319_p2 = (tmp_fu_297_p3 + zext_ln12_fu_315_p1);

assign add_ln15_fu_309_p2 = (tmp_fu_297_p3 + zext_ln15_fu_305_p1);

assign add_ln6_1_fu_198_p2 = (ap_sig_allocacmp_indvar_flatten131_load + 12'd1);

assign add_ln6_fu_227_p2 = (i_fu_72 + 5'd1);

assign add_ln7_1_fu_370_p2 = (indvar_flatten3_fu_76 + 10'd1);

assign add_ln7_fu_265_p2 = (select_ln6_fu_233_p3 + 5'd1);

assign and_ln6_fu_247_p2 = (xor_ln6_fu_241_p2 & ap_phi_mux_icmp_ln97_phi_fu_152_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_162 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1));
end

always @ (*) begin
    ap_condition_164 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_6_fu_285_p1 = k_mid2_fu_277_p3[3:0];

assign empty_fu_271_p2 = (ap_phi_mux_icmp_ln78_phi_fu_141_p4 | and_ln6_fu_247_p2);

assign i_3_fu_253_p3 = ((ap_phi_mux_icmp_ln78_phi_fu_141_p4[0:0] == 1'b1) ? add_ln6_fu_227_p2 : i_fu_72);

assign icmp_ln11_fu_353_p2 = (($signed(zext_ln9_fu_349_p1) < $signed(size_read_reg_484)) ? 1'b1 : 1'b0);

assign icmp_ln6_fu_204_p2 = ((ap_sig_allocacmp_indvar_flatten131_load == 12'd4095) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_384_p2 = ((select_ln7_1_fu_376_p3 == 10'd256) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_364_p2 = ((k_3_fu_358_p2 == 5'd16) ? 1'b1 : 1'b0);

assign in1_address0 = zext_ln12_1_fu_325_p1;

assign in1_ce0 = in1_ce0_local;

assign in2_address0 = zext_ln12_2_fu_344_p1;

assign in2_ce0 = in2_ce0_local;

assign j_3_fu_289_p3 = ((and_ln6_fu_247_p2[0:0] == 1'b1) ? add_ln7_fu_265_p2 : select_ln6_fu_233_p3);

assign k_3_fu_358_p2 = (k_mid2_fu_277_p3 + 5'd1);

assign k_mid2_fu_277_p3 = ((empty_fu_271_p2[0:0] == 1'b1) ? 5'd0 : k_fu_84);

assign out_r_address0 = zext_ln15_1_fu_420_p1;

assign out_r_ce0 = out_r_ce0_local;

assign out_r_d0 = sum_1_fu_429_p3;

assign out_r_we0 = out_r_we0_local;

assign select_ln6_fu_233_p3 = ((ap_phi_mux_icmp_ln78_phi_fu_141_p4[0:0] == 1'b1) ? 5'd0 : j_fu_80);

assign select_ln7_1_fu_376_p3 = ((ap_phi_mux_icmp_ln78_phi_fu_141_p4[0:0] == 1'b1) ? 10'd1 : add_ln7_1_fu_370_p2);

assign sum_1_fu_429_p3 = ((icmp_ln11_reg_513_pp0_iter3_reg[0:0] == 1'b1) ? sum_4_fu_424_p2 : sum_mid2_fu_413_p3);

assign sum_4_fu_424_p2 = (mul_ln12_reg_538 + sum_mid2_fu_413_p3);

assign sum_mid2_fu_413_p3 = ((empty_reg_493_pp0_iter3_reg[0:0] == 1'b1) ? 32'd0 : sum_fu_88);

assign tmp_1_fu_330_p3 = {{empty_6_fu_285_p1}, {4'd0}};

assign tmp_fu_297_p3 = {{trunc_ln7_fu_261_p1}, {4'd0}};

assign trunc_ln7_fu_261_p1 = i_3_fu_253_p3[3:0];

assign xor_ln6_fu_241_p2 = (ap_phi_mux_icmp_ln78_phi_fu_141_p4 ^ 1'd1);

assign zext_ln12_1_fu_325_p1 = add_ln12_fu_319_p2;

assign zext_ln12_2_fu_344_p1 = add_ln12_1_fu_338_p2;

assign zext_ln12_fu_315_p1 = k_mid2_fu_277_p3;

assign zext_ln15_1_fu_420_p1 = add_ln15_reg_498_pp0_iter3_reg;

assign zext_ln15_fu_305_p1 = j_3_fu_289_p3;

assign zext_ln9_fu_349_p1 = k_mid2_fu_277_p3;

endmodule //matmul
