# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_2c/design_2c.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2c || ORIG_REF_NAME==design_2c} -quiet] -quiet

# IP: bd/design_2c/ip/design_2c_processing_system7_0_0/design_2c_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2c_processing_system7_0_0 || ORIG_REF_NAME==design_2c_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_2c/ip/design_2c_axi_gpio_0_0/design_2c_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2c_axi_gpio_0_0 || ORIG_REF_NAME==design_2c_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_2c/ip/design_2c_xbar_0/design_2c_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2c_xbar_0 || ORIG_REF_NAME==design_2c_xbar_0} -quiet] -quiet

# IP: bd/design_2c/ip/design_2c_ps7_0_axi_periph_0/design_2c_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2c_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_2c_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_2c/ip/design_2c_rst_ps7_0_50M_0/design_2c_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2c_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_2c_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_2c/ip/design_2c_axi_gpio_1_0/design_2c_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2c_axi_gpio_1_0 || ORIG_REF_NAME==design_2c_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_2c/ip/design_2c_auto_pc_0/design_2c_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2c_auto_pc_0 || ORIG_REF_NAME==design_2c_auto_pc_0} -quiet] -quiet

# XDC: c:/DDisk/HK_II_nam3_dot_2/HW_SW/Vitis/week2/Project_2C/Project_2C.gen/sources_1/bd/design_2c/design_2c_ooc.xdc
