-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matmul is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    in1_ce0 : OUT STD_LOGIC;
    in1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    in1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    in1_ce1 : OUT STD_LOGIC;
    in1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    in2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    in2_ce0 : OUT STD_LOGIC;
    in2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    in2_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    in2_ce1 : OUT STD_LOGIC;
    in2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    out_r_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_r_ce0 : OUT STD_LOGIC;
    out_r_we0 : OUT STD_LOGIC;
    out_r_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    size : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of matmul is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matmul_matmul,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=2052,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=728,HLS_SYN_LUT=2331,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv28_0 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv6_10 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv7_30 : STD_LOGIC_VECTOR (6 downto 0) := "0110000";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv7_50 : STD_LOGIC_VECTOR (6 downto 0) := "1010000";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv8_70 : STD_LOGIC_VECTOR (7 downto 0) := "01110000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv8_90 : STD_LOGIC_VECTOR (7 downto 0) := "10010000";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv8_B0 : STD_LOGIC_VECTOR (7 downto 0) := "10110000";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage7 : signal is "none";
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln6_fu_1230_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage7 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage6 : signal is "none";
    signal ap_block_pp0_stage6_11001 : BOOLEAN;
    signal ap_block_pp0_stage7_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal grp_fu_477_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_509 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_483_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_513 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln10_fu_517_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_reg_1344 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_1_fu_533_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_1_reg_1349 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_2_fu_539_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_2_reg_1354 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_3_fu_555_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_3_reg_1359 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_4_fu_561_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_4_reg_1364 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_5_fu_567_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_5_reg_1369 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_6_fu_573_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_6_reg_1374 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_7_fu_589_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_7_reg_1379 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_8_fu_595_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_8_reg_1384 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_9_fu_601_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_9_reg_1389 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_10_fu_607_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_10_reg_1394 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_11_fu_613_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_11_reg_1399 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_12_fu_619_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_12_reg_1404 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_12_reg_1404_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_13_fu_625_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_13_reg_1409 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_13_reg_1409_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_14_fu_631_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_14_reg_1414 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_14_reg_1414_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_15_fu_647_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_15_reg_1419 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_15_reg_1419_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln6_fu_680_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln6_reg_1424 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln11_fu_696_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln11_reg_1433 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_700_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_reg_1451 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln11_18_fu_731_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln11_18_reg_1466 : STD_LOGIC_VECTOR (5 downto 0);
    signal bit_sel_reg_1481 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln11_1_fu_754_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln11_1_reg_1486 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_17_fu_787_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln11_17_reg_1501 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_16_cast_fu_790_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_16_cast_reg_1507 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_cast_fu_837_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_17_cast_reg_1533 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln11_2_fu_849_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln11_2_reg_1543 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln11_16_fu_883_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln11_16_reg_1563 : STD_LOGIC_VECTOR (7 downto 0);
    signal sum_3_fu_918_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_reg_1580 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_7_fu_988_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_7_reg_1606 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_fu_1041_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln14_reg_1632 : STD_LOGIC_VECTOR (7 downto 0);
    signal sum_11_fu_1062_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_11_reg_1637 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_15_fu_1126_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_15_reg_1663 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_19_fu_1206_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_19_reg_1689 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln7_fu_1224_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_reg_1695 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln6_reg_1700 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_23_fu_1263_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_23_reg_1704 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_27_fu_1287_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_27_reg_1710 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_phi_mux_icmp_ln74_phi_fu_470_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln11_fu_708_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_1_fu_721_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln7_fu_726_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_19_fu_741_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_2_fu_770_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln11_3_fu_782_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_20_fu_797_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_21_fu_808_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_4_fu_820_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal zext_ln11_5_fu_832_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_22_fu_844_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_23_fu_854_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_6_fu_866_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal zext_ln11_7_fu_878_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_24_fu_889_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_25_fu_900_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_8_fu_932_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal zext_ln11_9_fu_944_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_26_fu_956_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_27_fu_966_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_10_fu_1002_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage5 : BOOLEAN;
    signal zext_ln11_11_fu_1014_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_28_fu_1026_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_29_fu_1036_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_12_fu_1076_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage6 : BOOLEAN;
    signal zext_ln11_13_fu_1088_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_30_fu_1096_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_31_fu_1104_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_14_fu_1143_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage7 : BOOLEAN;
    signal zext_ln11_15_fu_1155_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_32_fu_1163_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_33_fu_1184_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_fu_1294_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten1_fu_162 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln6_1_fu_1218_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_fu_166 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal i_3_fu_688_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal j_fu_170 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal j_3_fu_1213_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_j_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal in1_ce1_local : STD_LOGIC;
    signal in1_address1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal in1_ce0_local : STD_LOGIC;
    signal in1_address0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal in2_ce1_local : STD_LOGIC;
    signal in2_address1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal in2_ce0_local : STD_LOGIC;
    signal in2_address0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal out_r_we0_local : STD_LOGIC;
    signal sum_31_fu_1315_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_r_ce0_local : STD_LOGIC;
    signal tmp_16_fu_523_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_17_fu_545_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_18_fu_579_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_19_fu_637_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal add_ln6_fu_674_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_1_fu_713_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln11_fu_735_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_763_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_775_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln11_1_fu_802_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_4_fu_813_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_825_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_859_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_871_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln11_fu_886_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln11_3_fu_894_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sum_1_fu_905_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_2_fu_912_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_925_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_fu_937_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_19_cast_fu_949_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln11_4_fu_961_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sum_4_fu_971_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_5_fu_976_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_6_fu_982_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_995_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_10_fu_1007_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_20_cast_fu_1019_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln11_5_fu_1031_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sum_8_fu_1045_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_9_fu_1050_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_10_fu_1056_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_1069_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_12_fu_1081_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln11_1_fu_1093_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln11_2_fu_1101_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sum_12_fu_1109_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_13_fu_1114_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_14_fu_1120_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_13_fu_1136_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_14_fu_1148_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln11_3_fu_1160_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln11_fu_1168_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln11_7_fu_1173_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln11_4_fu_1180_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sum_16_fu_1189_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_17_fu_1194_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_18_fu_1200_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_20_fu_1246_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_21_fu_1251_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_22_fu_1257_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_24_fu_1270_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_25_fu_1275_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_26_fu_1281_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_28_fu_1298_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_29_fu_1303_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_30_fu_1309_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter1_stage2 : STD_LOGIC;
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_1126 : BOOLEAN;
    signal ap_condition_460 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component matmul_mul_32s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component matmul_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    mul_32s_32s_32_2_1_U1 : component matmul_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => in2_q1,
        din1 => in1_q1,
        ce => ap_const_logic_1,
        dout => grp_fu_477_p2);

    mul_32s_32s_32_2_1_U2 : component matmul_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => in2_q0,
        din1 => in1_q0,
        ce => ap_const_logic_1,
        dout => grp_fu_483_p2);

    flow_control_loop_pipe_U : component matmul_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage7,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_loop_exit_ready = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage2) and (ap_idle_pp0_0to0 = ap_const_logic_1)))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    i_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_460)) then
                i_fu_166 <= i_3_fu_688_p3;
            end if;
        end if;
    end process;

    indvar_flatten1_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten1_fu_162 <= ap_const_lv8_0;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                indvar_flatten1_fu_162 <= add_ln6_1_fu_1218_p2;
            end if; 
        end if;
    end process;

    j_fu_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                j_fu_170 <= ap_const_lv5_0;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                j_fu_170 <= j_3_fu_1213_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                add_ln11_2_reg_1543 <= add_ln11_2_fu_849_p2;
                    tmp_17_cast_reg_1533(4 downto 0) <= tmp_17_cast_fu_837_p3(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then
                add_ln14_reg_1632 <= add_ln14_fu_1041_p2;
                sum_11_reg_1637 <= sum_11_fu_1062_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                bit_sel_reg_1481 <= select_ln6_fu_680_p3(4 downto 4);
                icmp_ln10_10_reg_1394 <= icmp_ln10_10_fu_607_p2;
                icmp_ln10_11_reg_1399 <= icmp_ln10_11_fu_613_p2;
                icmp_ln10_12_reg_1404 <= icmp_ln10_12_fu_619_p2;
                icmp_ln10_12_reg_1404_pp0_iter1_reg <= icmp_ln10_12_reg_1404;
                icmp_ln10_13_reg_1409 <= icmp_ln10_13_fu_625_p2;
                icmp_ln10_13_reg_1409_pp0_iter1_reg <= icmp_ln10_13_reg_1409;
                icmp_ln10_14_reg_1414 <= icmp_ln10_14_fu_631_p2;
                icmp_ln10_14_reg_1414_pp0_iter1_reg <= icmp_ln10_14_reg_1414;
                icmp_ln10_15_reg_1419 <= icmp_ln10_15_fu_647_p2;
                icmp_ln10_15_reg_1419_pp0_iter1_reg <= icmp_ln10_15_reg_1419;
                icmp_ln10_1_reg_1349 <= icmp_ln10_1_fu_533_p2;
                icmp_ln10_2_reg_1354 <= icmp_ln10_2_fu_539_p2;
                icmp_ln10_3_reg_1359 <= icmp_ln10_3_fu_555_p2;
                icmp_ln10_4_reg_1364 <= icmp_ln10_4_fu_561_p2;
                icmp_ln10_5_reg_1369 <= icmp_ln10_5_fu_567_p2;
                icmp_ln10_6_reg_1374 <= icmp_ln10_6_fu_573_p2;
                icmp_ln10_7_reg_1379 <= icmp_ln10_7_fu_589_p2;
                icmp_ln10_8_reg_1384 <= icmp_ln10_8_fu_595_p2;
                icmp_ln10_9_reg_1389 <= icmp_ln10_9_fu_601_p2;
                icmp_ln10_reg_1344 <= icmp_ln10_fu_517_p2;
                select_ln6_reg_1424 <= select_ln6_fu_680_p3;
                sum_23_reg_1704 <= sum_23_fu_1263_p3;
                    tmp_reg_1451(7 downto 4) <= tmp_fu_700_p3(7 downto 4);
                trunc_ln11_1_reg_1486 <= trunc_ln11_1_fu_754_p1;
                trunc_ln11_reg_1433 <= trunc_ln11_fu_696_p1;
                    zext_ln11_18_reg_1466(4 downto 0) <= zext_ln11_18_fu_731_p1(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then
                icmp_ln6_reg_1700 <= icmp_ln6_fu_1230_p2;
                sum_19_reg_1689 <= sum_19_fu_1206_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then
                icmp_ln7_reg_1695 <= icmp_ln7_fu_1224_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 
    = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then
                reg_509 <= grp_fu_477_p2;
                reg_513 <= grp_fu_483_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then
                sum_15_reg_1663 <= sum_15_fu_1126_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                sum_27_reg_1710 <= sum_27_fu_1287_p3;
                    tmp_16_cast_reg_1507(4 downto 0) <= tmp_16_cast_fu_790_p3(4 downto 0);
                    zext_ln11_17_reg_1501(4 downto 0) <= zext_ln11_17_fu_787_p1(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                sum_3_reg_1580 <= sum_3_fu_918_p3;
                    zext_ln11_16_reg_1563(4 downto 0) <= zext_ln11_16_fu_883_p1(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                sum_7_reg_1606 <= sum_7_fu_988_p3;
            end if;
        end if;
    end process;
    tmp_reg_1451(3 downto 0) <= "0000";
    zext_ln11_18_reg_1466(5) <= '0';
    zext_ln11_17_reg_1501(6 downto 5) <= "00";
    tmp_16_cast_reg_1507(5) <= '1';
    tmp_17_cast_reg_1533(6 downto 5) <= "10";
    zext_ln11_16_reg_1563(7 downto 5) <= "000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage7_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter1_stage2, ap_idle_pp0_0to0, ap_block_pp0_stage1_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if (((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage2) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln11_1_fu_802_p2 <= std_logic_vector(unsigned(zext_ln11_17_fu_787_p1) + unsigned(ap_const_lv7_30));
    add_ln11_2_fu_849_p2 <= std_logic_vector(unsigned(zext_ln11_17_reg_1501) + unsigned(ap_const_lv7_50));
    add_ln11_3_fu_894_p2 <= std_logic_vector(unsigned(zext_ln11_16_fu_883_p1) + unsigned(ap_const_lv8_70));
    add_ln11_4_fu_961_p2 <= std_logic_vector(unsigned(zext_ln11_16_reg_1563) + unsigned(ap_const_lv8_90));
    add_ln11_5_fu_1031_p2 <= std_logic_vector(unsigned(zext_ln11_16_reg_1563) + unsigned(ap_const_lv8_B0));
    add_ln11_7_fu_1173_p3 <= (xor_ln11_fu_1168_p2 & trunc_ln11_1_reg_1486);
    add_ln11_fu_735_p2 <= std_logic_vector(unsigned(zext_ln11_18_fu_731_p1) + unsigned(ap_const_lv6_10));
    add_ln14_fu_1041_p2 <= std_logic_vector(unsigned(tmp_reg_1451) + unsigned(zext_ln11_16_reg_1563));
    add_ln6_1_fu_1218_p2 <= std_logic_vector(unsigned(indvar_flatten1_fu_162) + unsigned(ap_const_lv8_1));
    add_ln6_fu_674_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
    ap_CS_fsm_pp0_stage6 <= ap_CS_fsm(6);
    ap_CS_fsm_pp0_stage7 <= ap_CS_fsm(7);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_1126_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln6_reg_1700, ap_block_pp0_stage0)
    begin
                ap_condition_1126 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln6_reg_1700 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_460_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_460 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage7_assign_proc : process(ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln6_fu_1230_p2)
    begin
        if (((icmp_ln6_fu_1230_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            ap_condition_exit_pp0_iter0_stage7 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage7 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, icmp_ln6_reg_1700, ap_block_pp0_stage2_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (icmp_ln6_reg_1700 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter1_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage7;

    ap_phi_mux_icmp_ln74_phi_fu_470_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln7_reg_1695, ap_loop_init, ap_condition_1126)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_1126)) then 
                ap_phi_mux_icmp_ln74_phi_fu_470_p4 <= icmp_ln7_reg_1695;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_icmp_ln74_phi_fu_470_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_icmp_ln74_phi_fu_470_p4 <= icmp_ln7_reg_1695;
            end if;
        else 
            ap_phi_mux_icmp_ln74_phi_fu_470_p4 <= icmp_ln7_reg_1695;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, i_fu_166)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_166;
        end if; 
    end process;


    ap_sig_allocacmp_j_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, j_fu_170)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_j_1 <= j_fu_170;
        end if; 
    end process;

    i_3_fu_688_p3 <= 
        add_ln6_fu_674_p2 when (ap_phi_mux_icmp_ln74_phi_fu_470_p4(0) = '1') else 
        ap_sig_allocacmp_i_1;
    icmp_ln10_10_fu_607_p2 <= "1" when (signed(size) > signed(ap_const_lv32_A)) else "0";
    icmp_ln10_11_fu_613_p2 <= "1" when (signed(size) > signed(ap_const_lv32_B)) else "0";
    icmp_ln10_12_fu_619_p2 <= "1" when (signed(size) > signed(ap_const_lv32_C)) else "0";
    icmp_ln10_13_fu_625_p2 <= "1" when (signed(size) > signed(ap_const_lv32_D)) else "0";
    icmp_ln10_14_fu_631_p2 <= "1" when (signed(size) > signed(ap_const_lv32_E)) else "0";
    icmp_ln10_15_fu_647_p2 <= "1" when (signed(tmp_19_fu_637_p4) > signed(ap_const_lv28_0)) else "0";
    icmp_ln10_1_fu_533_p2 <= "1" when (signed(tmp_16_fu_523_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln10_2_fu_539_p2 <= "1" when (signed(size) > signed(ap_const_lv32_2)) else "0";
    icmp_ln10_3_fu_555_p2 <= "1" when (signed(tmp_17_fu_545_p4) > signed(ap_const_lv30_0)) else "0";
    icmp_ln10_4_fu_561_p2 <= "1" when (signed(size) > signed(ap_const_lv32_4)) else "0";
    icmp_ln10_5_fu_567_p2 <= "1" when (signed(size) > signed(ap_const_lv32_5)) else "0";
    icmp_ln10_6_fu_573_p2 <= "1" when (signed(size) > signed(ap_const_lv32_6)) else "0";
    icmp_ln10_7_fu_589_p2 <= "1" when (signed(tmp_18_fu_579_p4) > signed(ap_const_lv29_0)) else "0";
    icmp_ln10_8_fu_595_p2 <= "1" when (signed(size) > signed(ap_const_lv32_8)) else "0";
    icmp_ln10_9_fu_601_p2 <= "1" when (signed(size) > signed(ap_const_lv32_9)) else "0";
    icmp_ln10_fu_517_p2 <= "1" when (signed(size) > signed(ap_const_lv32_0)) else "0";
    icmp_ln6_fu_1230_p2 <= "1" when (indvar_flatten1_fu_162 = ap_const_lv8_FF) else "0";
    icmp_ln7_fu_1224_p2 <= "1" when (j_3_fu_1213_p2 = ap_const_lv5_10) else "0";
    in1_address0 <= in1_address0_local;

    in1_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage0, zext_ln11_1_fu_721_p1, ap_block_pp0_stage1, zext_ln11_3_fu_782_p1, ap_block_pp0_stage2, zext_ln11_5_fu_832_p1, ap_block_pp0_stage3, zext_ln11_7_fu_878_p1, ap_block_pp0_stage4, zext_ln11_9_fu_944_p1, ap_block_pp0_stage5, zext_ln11_11_fu_1014_p1, ap_block_pp0_stage6, zext_ln11_13_fu_1088_p1, ap_block_pp0_stage7, zext_ln11_15_fu_1155_p1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            in1_address0_local <= zext_ln11_15_fu_1155_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            in1_address0_local <= zext_ln11_13_fu_1088_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            in1_address0_local <= zext_ln11_11_fu_1014_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            in1_address0_local <= zext_ln11_9_fu_944_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            in1_address0_local <= zext_ln11_7_fu_878_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            in1_address0_local <= zext_ln11_5_fu_832_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            in1_address0_local <= zext_ln11_3_fu_782_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in1_address0_local <= zext_ln11_1_fu_721_p1(8 - 1 downto 0);
        else 
            in1_address0_local <= "XXXXXXXX";
        end if; 
    end process;

    in1_address1 <= in1_address1_local;

    in1_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage0, zext_ln11_fu_708_p1, zext_ln11_2_fu_770_p1, ap_block_pp0_stage1, zext_ln11_4_fu_820_p1, ap_block_pp0_stage2, zext_ln11_6_fu_866_p1, ap_block_pp0_stage3, zext_ln11_8_fu_932_p1, ap_block_pp0_stage4, zext_ln11_10_fu_1002_p1, ap_block_pp0_stage5, zext_ln11_12_fu_1076_p1, ap_block_pp0_stage6, zext_ln11_14_fu_1143_p1, ap_block_pp0_stage7)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            in1_address1_local <= zext_ln11_14_fu_1143_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            in1_address1_local <= zext_ln11_12_fu_1076_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            in1_address1_local <= zext_ln11_10_fu_1002_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            in1_address1_local <= zext_ln11_8_fu_932_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            in1_address1_local <= zext_ln11_6_fu_866_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            in1_address1_local <= zext_ln11_4_fu_820_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            in1_address1_local <= zext_ln11_2_fu_770_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in1_address1_local <= zext_ln11_fu_708_p1(8 - 1 downto 0);
        else 
            in1_address1_local <= "XXXXXXXX";
        end if; 
    end process;

    in1_ce0 <= in1_ce0_local;

    in1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_11001, ap_block_pp0_stage7_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and 
    (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            in1_ce0_local <= ap_const_logic_1;
        else 
            in1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in1_ce1 <= in1_ce1_local;

    in1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_11001, ap_block_pp0_stage7_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and 
    (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            in1_ce1_local <= ap_const_logic_1;
        else 
            in1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    in2_address0 <= in2_address0_local;

    in2_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage0, zext_ln11_19_fu_741_p1, ap_block_pp0_stage1, zext_ln11_21_fu_808_p1, ap_block_pp0_stage2, zext_ln11_23_fu_854_p1, ap_block_pp0_stage3, zext_ln11_25_fu_900_p1, ap_block_pp0_stage4, zext_ln11_27_fu_966_p1, ap_block_pp0_stage5, zext_ln11_29_fu_1036_p1, ap_block_pp0_stage6, zext_ln11_31_fu_1104_p1, ap_block_pp0_stage7, zext_ln11_33_fu_1184_p1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            in2_address0_local <= zext_ln11_33_fu_1184_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            in2_address0_local <= zext_ln11_31_fu_1104_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            in2_address0_local <= zext_ln11_29_fu_1036_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            in2_address0_local <= zext_ln11_27_fu_966_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            in2_address0_local <= zext_ln11_25_fu_900_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            in2_address0_local <= zext_ln11_23_fu_854_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            in2_address0_local <= zext_ln11_21_fu_808_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in2_address0_local <= zext_ln11_19_fu_741_p1(8 - 1 downto 0);
        else 
            in2_address0_local <= "XXXXXXXX";
        end if; 
    end process;

    in2_address1 <= in2_address1_local;

    in2_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage0, zext_ln7_fu_726_p1, ap_block_pp0_stage1, zext_ln11_20_fu_797_p1, ap_block_pp0_stage2, zext_ln11_22_fu_844_p1, ap_block_pp0_stage3, zext_ln11_24_fu_889_p1, ap_block_pp0_stage4, zext_ln11_26_fu_956_p1, ap_block_pp0_stage5, zext_ln11_28_fu_1026_p1, ap_block_pp0_stage6, zext_ln11_30_fu_1096_p1, ap_block_pp0_stage7, zext_ln11_32_fu_1163_p1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            in2_address1_local <= zext_ln11_32_fu_1163_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            in2_address1_local <= zext_ln11_30_fu_1096_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            in2_address1_local <= zext_ln11_28_fu_1026_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            in2_address1_local <= zext_ln11_26_fu_956_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            in2_address1_local <= zext_ln11_24_fu_889_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            in2_address1_local <= zext_ln11_22_fu_844_p1(8 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            in2_address1_local <= zext_ln11_20_fu_797_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in2_address1_local <= zext_ln7_fu_726_p1(8 - 1 downto 0);
        else 
            in2_address1_local <= "XXXXXXXX";
        end if; 
    end process;

    in2_ce0 <= in2_ce0_local;

    in2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_11001, ap_block_pp0_stage7_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and 
    (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            in2_ce0_local <= ap_const_logic_1;
        else 
            in2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in2_ce1 <= in2_ce1_local;

    in2_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_11001, ap_block_pp0_stage7_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and 
    (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            in2_ce1_local <= ap_const_logic_1;
        else 
            in2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    j_3_fu_1213_p2 <= std_logic_vector(unsigned(select_ln6_reg_1424) + unsigned(ap_const_lv5_1));
    out_r_address0 <= zext_ln14_fu_1294_p1(8 - 1 downto 0);
    out_r_ce0 <= out_r_ce0_local;

    out_r_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            out_r_ce0_local <= ap_const_logic_1;
        else 
            out_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    out_r_d0 <= sum_31_fu_1315_p3;
    out_r_we0 <= out_r_we0_local;

    out_r_we0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            out_r_we0_local <= ap_const_logic_1;
        else 
            out_r_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln6_fu_680_p3 <= 
        ap_const_lv5_0 when (ap_phi_mux_icmp_ln74_phi_fu_470_p4(0) = '1') else 
        ap_sig_allocacmp_j_1;
        sext_ln11_1_fu_1093_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_17_cast_reg_1533),8));

        sext_ln11_2_fu_1101_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln11_2_reg_1543),8));

        sext_ln11_3_fu_1160_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_16_cast_reg_1507),8));

        sext_ln11_4_fu_1180_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln11_7_fu_1173_p3),8));

        sext_ln11_fu_886_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_16_cast_reg_1507),7));

    sum_10_fu_1056_p2 <= std_logic_vector(unsigned(reg_513) + unsigned(sum_9_fu_1050_p3));
    sum_11_fu_1062_p3 <= 
        sum_10_fu_1056_p2 when (icmp_ln10_5_reg_1369(0) = '1') else 
        sum_9_fu_1050_p3;
    sum_12_fu_1109_p2 <= std_logic_vector(unsigned(reg_509) + unsigned(sum_11_reg_1637));
    sum_13_fu_1114_p3 <= 
        sum_12_fu_1109_p2 when (icmp_ln10_6_reg_1374(0) = '1') else 
        sum_11_reg_1637;
    sum_14_fu_1120_p2 <= std_logic_vector(unsigned(reg_513) + unsigned(sum_13_fu_1114_p3));
    sum_15_fu_1126_p3 <= 
        sum_14_fu_1120_p2 when (icmp_ln10_7_reg_1379(0) = '1') else 
        sum_13_fu_1114_p3;
    sum_16_fu_1189_p2 <= std_logic_vector(unsigned(reg_509) + unsigned(sum_15_reg_1663));
    sum_17_fu_1194_p3 <= 
        sum_16_fu_1189_p2 when (icmp_ln10_8_reg_1384(0) = '1') else 
        sum_15_reg_1663;
    sum_18_fu_1200_p2 <= std_logic_vector(unsigned(reg_513) + unsigned(sum_17_fu_1194_p3));
    sum_19_fu_1206_p3 <= 
        sum_18_fu_1200_p2 when (icmp_ln10_9_reg_1389(0) = '1') else 
        sum_17_fu_1194_p3;
    sum_1_fu_905_p3 <= 
        reg_509 when (icmp_ln10_reg_1344(0) = '1') else 
        ap_const_lv32_0;
    sum_20_fu_1246_p2 <= std_logic_vector(unsigned(reg_509) + unsigned(sum_19_reg_1689));
    sum_21_fu_1251_p3 <= 
        sum_20_fu_1246_p2 when (icmp_ln10_10_reg_1394(0) = '1') else 
        sum_19_reg_1689;
    sum_22_fu_1257_p2 <= std_logic_vector(unsigned(reg_513) + unsigned(sum_21_fu_1251_p3));
    sum_23_fu_1263_p3 <= 
        sum_22_fu_1257_p2 when (icmp_ln10_11_reg_1399(0) = '1') else 
        sum_21_fu_1251_p3;
    sum_24_fu_1270_p2 <= std_logic_vector(unsigned(reg_509) + unsigned(sum_23_reg_1704));
    sum_25_fu_1275_p3 <= 
        sum_24_fu_1270_p2 when (icmp_ln10_12_reg_1404_pp0_iter1_reg(0) = '1') else 
        sum_23_reg_1704;
    sum_26_fu_1281_p2 <= std_logic_vector(unsigned(reg_513) + unsigned(sum_25_fu_1275_p3));
    sum_27_fu_1287_p3 <= 
        sum_26_fu_1281_p2 when (icmp_ln10_13_reg_1409_pp0_iter1_reg(0) = '1') else 
        sum_25_fu_1275_p3;
    sum_28_fu_1298_p2 <= std_logic_vector(unsigned(reg_509) + unsigned(sum_27_reg_1710));
    sum_29_fu_1303_p3 <= 
        sum_28_fu_1298_p2 when (icmp_ln10_14_reg_1414_pp0_iter1_reg(0) = '1') else 
        sum_27_reg_1710;
    sum_2_fu_912_p2 <= std_logic_vector(unsigned(reg_513) + unsigned(sum_1_fu_905_p3));
    sum_30_fu_1309_p2 <= std_logic_vector(unsigned(reg_513) + unsigned(sum_29_fu_1303_p3));
    sum_31_fu_1315_p3 <= 
        sum_30_fu_1309_p2 when (icmp_ln10_15_reg_1419_pp0_iter1_reg(0) = '1') else 
        sum_29_fu_1303_p3;
    sum_3_fu_918_p3 <= 
        sum_2_fu_912_p2 when (icmp_ln10_1_reg_1349(0) = '1') else 
        sum_1_fu_905_p3;
    sum_4_fu_971_p2 <= std_logic_vector(unsigned(reg_509) + unsigned(sum_3_reg_1580));
    sum_5_fu_976_p3 <= 
        sum_4_fu_971_p2 when (icmp_ln10_2_reg_1354(0) = '1') else 
        sum_3_reg_1580;
    sum_6_fu_982_p2 <= std_logic_vector(unsigned(reg_513) + unsigned(sum_5_fu_976_p3));
    sum_7_fu_988_p3 <= 
        sum_6_fu_982_p2 when (icmp_ln10_3_reg_1359(0) = '1') else 
        sum_5_fu_976_p3;
    sum_8_fu_1045_p2 <= std_logic_vector(unsigned(reg_509) + unsigned(sum_7_reg_1606));
    sum_9_fu_1050_p3 <= 
        sum_8_fu_1045_p2 when (icmp_ln10_4_reg_1364(0) = '1') else 
        sum_7_reg_1606;
    tmp_10_fu_1007_p3 <= (trunc_ln11_reg_1433 & ap_const_lv4_B);
    tmp_11_fu_1069_p3 <= (trunc_ln11_reg_1433 & ap_const_lv4_C);
    tmp_12_fu_1081_p3 <= (trunc_ln11_reg_1433 & ap_const_lv4_D);
    tmp_13_fu_1136_p3 <= (trunc_ln11_reg_1433 & ap_const_lv4_E);
    tmp_14_fu_1148_p3 <= (trunc_ln11_reg_1433 & ap_const_lv4_F);
    tmp_16_cast_fu_790_p3 <= (ap_const_lv1_1 & select_ln6_reg_1424);
    tmp_16_fu_523_p4 <= size(31 downto 1);
    tmp_17_cast_fu_837_p3 <= (ap_const_lv1_1 & zext_ln11_18_reg_1466);
    tmp_17_fu_545_p4 <= size(31 downto 2);
    tmp_18_fu_579_p4 <= size(31 downto 3);
    tmp_19_cast_fu_949_p3 <= (ap_const_lv1_1 & zext_ln11_17_reg_1501);
    tmp_19_fu_637_p4 <= size(31 downto 4);
    tmp_1_fu_713_p3 <= (trunc_ln11_fu_696_p1 & ap_const_lv4_1);
    tmp_20_cast_fu_1019_p3 <= (ap_const_lv3_5 & select_ln6_reg_1424);
    tmp_2_fu_763_p3 <= (trunc_ln11_reg_1433 & ap_const_lv4_2);
    tmp_3_fu_775_p3 <= (trunc_ln11_reg_1433 & ap_const_lv4_3);
    tmp_4_fu_813_p3 <= (trunc_ln11_reg_1433 & ap_const_lv4_4);
    tmp_5_fu_825_p3 <= (trunc_ln11_reg_1433 & ap_const_lv4_5);
    tmp_6_fu_859_p3 <= (trunc_ln11_reg_1433 & ap_const_lv4_6);
    tmp_7_fu_871_p3 <= (trunc_ln11_reg_1433 & ap_const_lv4_7);
    tmp_8_fu_925_p3 <= (trunc_ln11_reg_1433 & ap_const_lv4_8);
    tmp_9_fu_937_p3 <= (trunc_ln11_reg_1433 & ap_const_lv4_9);
    tmp_fu_700_p3 <= (trunc_ln11_fu_696_p1 & ap_const_lv4_0);
    tmp_s_fu_995_p3 <= (trunc_ln11_reg_1433 & ap_const_lv4_A);
    trunc_ln11_1_fu_754_p1 <= select_ln6_fu_680_p3(4 - 1 downto 0);
    trunc_ln11_fu_696_p1 <= i_3_fu_688_p3(4 - 1 downto 0);
    xor_ln11_fu_1168_p2 <= (bit_sel_reg_1481 xor ap_const_lv1_1);
    zext_ln11_10_fu_1002_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_995_p3),64));
    zext_ln11_11_fu_1014_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_1007_p3),64));
    zext_ln11_12_fu_1076_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_1069_p3),64));
    zext_ln11_13_fu_1088_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_1081_p3),64));
    zext_ln11_14_fu_1143_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_13_fu_1136_p3),64));
    zext_ln11_15_fu_1155_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_14_fu_1148_p3),64));
    zext_ln11_16_fu_883_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln6_reg_1424),8));
    zext_ln11_17_fu_787_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln6_reg_1424),7));
    zext_ln11_18_fu_731_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln6_fu_680_p3),6));
    zext_ln11_19_fu_741_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_fu_735_p2),64));
    zext_ln11_1_fu_721_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_713_p3),64));
    zext_ln11_20_fu_797_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_16_cast_fu_790_p3),64));
    zext_ln11_21_fu_808_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_1_fu_802_p2),64));
    zext_ln11_22_fu_844_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_17_cast_fu_837_p3),64));
    zext_ln11_23_fu_854_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_2_fu_849_p2),64));
    zext_ln11_24_fu_889_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln11_fu_886_p1),64));
    zext_ln11_25_fu_900_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_3_fu_894_p2),64));
    zext_ln11_26_fu_956_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_19_cast_fu_949_p3),64));
    zext_ln11_27_fu_966_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_4_fu_961_p2),64));
    zext_ln11_28_fu_1026_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_20_cast_fu_1019_p3),64));
    zext_ln11_29_fu_1036_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_5_fu_1031_p2),64));
    zext_ln11_2_fu_770_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_763_p3),64));
    zext_ln11_30_fu_1096_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln11_1_fu_1093_p1),64));
    zext_ln11_31_fu_1104_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln11_2_fu_1101_p1),64));
    zext_ln11_32_fu_1163_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln11_3_fu_1160_p1),64));
    zext_ln11_33_fu_1184_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln11_4_fu_1180_p1),64));
    zext_ln11_3_fu_782_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_775_p3),64));
    zext_ln11_4_fu_820_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_813_p3),64));
    zext_ln11_5_fu_832_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_825_p3),64));
    zext_ln11_6_fu_866_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_859_p3),64));
    zext_ln11_7_fu_878_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_871_p3),64));
    zext_ln11_8_fu_932_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_925_p3),64));
    zext_ln11_9_fu_944_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_937_p3),64));
    zext_ln11_fu_708_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_700_p3),64));
    zext_ln14_fu_1294_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln14_reg_1632),64));
    zext_ln7_fu_726_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln6_fu_680_p3),64));
end behav;
