# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/blinking_led/blinking_led.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blinking_led || ORIG_REF_NAME==blinking_led} -quiet] -quiet

# IP: bd/blinking_led/ip/blinking_led_processing_system7_0_1/blinking_led_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blinking_led_processing_system7_0_1 || ORIG_REF_NAME==blinking_led_processing_system7_0_1} -quiet] -quiet

# IP: bd/blinking_led/ip/blinking_led_axi_gpio_0_1/blinking_led_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blinking_led_axi_gpio_0_1 || ORIG_REF_NAME==blinking_led_axi_gpio_0_1} -quiet] -quiet

# IP: bd/blinking_led/ip/blinking_led_axi_smc_2/blinking_led_axi_smc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blinking_led_axi_smc_2 || ORIG_REF_NAME==blinking_led_axi_smc_2} -quiet] -quiet

# IP: bd/blinking_led/ip/blinking_led_rst_ps7_0_50M_2/blinking_led_rst_ps7_0_50M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blinking_led_rst_ps7_0_50M_2 || ORIG_REF_NAME==blinking_led_rst_ps7_0_50M_2} -quiet] -quiet

# XDC: /home/nhanenten/Desktop/HW_SW/Lab1/Lab1.gen/sources_1/bd/blinking_led/blinking_led_ooc.xdc
