# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/DDisk/HK_II_nam3_dot_2/HW_SW/Vitis/week2/Project_2C/Project_2C.srcs/sources_1/bd/design_2c/ip/design_2c_axi_gpio_1_0/design_2c_axi_gpio_1_0.xci
# IP: The module: 'design_2c_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DDisk/HK_II_nam3_dot_2/HW_SW/Vitis/week2/Project_2C/Project_2C.gen/sources_1/bd/design_2c/ip/design_2c_axi_gpio_1_0/design_2c_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2c_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/DDisk/HK_II_nam3_dot_2/HW_SW/Vitis/week2/Project_2C/Project_2C.gen/sources_1/bd/design_2c/ip/design_2c_axi_gpio_1_0/design_2c_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2c_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/DDisk/HK_II_nam3_dot_2/HW_SW/Vitis/week2/Project_2C/Project_2C.gen/sources_1/bd/design_2c/ip/design_2c_axi_gpio_1_0/design_2c_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2c_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/DDisk/HK_II_nam3_dot_2/HW_SW/Vitis/week2/Project_2C/Project_2C.srcs/sources_1/bd/design_2c/ip/design_2c_axi_gpio_1_0/design_2c_axi_gpio_1_0.xci
# IP: The module: 'design_2c_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DDisk/HK_II_nam3_dot_2/HW_SW/Vitis/week2/Project_2C/Project_2C.gen/sources_1/bd/design_2c/ip/design_2c_axi_gpio_1_0/design_2c_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2c_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/DDisk/HK_II_nam3_dot_2/HW_SW/Vitis/week2/Project_2C/Project_2C.gen/sources_1/bd/design_2c/ip/design_2c_axi_gpio_1_0/design_2c_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2c_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/DDisk/HK_II_nam3_dot_2/HW_SW/Vitis/week2/Project_2C/Project_2C.gen/sources_1/bd/design_2c/ip/design_2c_axi_gpio_1_0/design_2c_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2c_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
